PERF: Speed up `geobuffer` via `UTM` CRS (#638)
* EHN: A sugary syntax wraps `joblib.Parallel`

this method could speed up some scenes like io

* index method

* expose `set_unique_index` to public

* index method

* index method

* speed up utm_crs

* Add raises section

* correct path

* speed up via transforming to utm crs

* simplify doc

* lint codes

* fix variable name

* lint codes

* use upper case words

* rename variable

* fix typeerror

TypeError: assign() takes 1 positional argument but 2 were given

* DEP: Add `DeprecationWarning` for `utm_crs`

* remove find_stack_level

* Revert "speed up utm_crs"

This reverts commit a45c6f53ad5046c5c88985f2df87432c3aad53b2.

* Ignore UserWarning ("Geometry is in a geographic CRS")

* reversed changes to parallelize

* test Series with duplicate index

* BOT: auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* Add example

* Handle None

* escape `{}`

* correct mark

* handle utm is nan

* test empty point

* BOT: auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* test non-wgs84 crs

* correct method naem

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>