ENH: `import dtoolkit` == `import dtoolkit.accessor` (#772)
* simplify importing

`import dtoolkit` == `import dtoolkit.accessor`

* simplify a bit

* BOT: auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* ignore f401

* BOT: auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* dynamically get version

AttributeError: module 'dtoolkit' has no attribute '__version__'

* use `license_files` instead of `license_file`

SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>